version: '3.8'

services:
  nginx:
    container_name: nginx
    image: muhammettncy/nginxx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/backend
    networks:
      - app-network
    depends_on:
      - product_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - DB_HOST=product_service_mysql
      - DB_PORT=3306
      - DB_DATABASE=product_service
      - DB_USERNAME=product_service
      - DB_PASSWORD=product_service

  product_service:
    container_name: product_service
    image: muhammettncy/product-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source:/var/www/backend
      - ./source/storage:/var/www/backend/storage
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    ports:
      - "9000:9000"

  product_service_mysql:
    container_name: product_service_mysql
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service
      MYSQL_USER: product_service
      MYSQL_PASSWORD: product_service
    networks:
      - app-network
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - app-network
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge